# Generated by Django 2.2.8 on 2020-11-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_auto_20201130_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
